### ISSUE TITLE
[BUG] Discord Bot failing to log forward for certain options

### ISSUE THREAD

**Issue by tristencommunity** [Blumlaut/EasyAdmin#428] opened 2022-06-26 07:52 UTC
**Describe the bug**
When you use the Discord bot to log forward certain options (*the only ones ive tested:* reports, report, calladmin), it fails to do so and redirects to the default log channel for the bot.

**To Reproduce**
1. Create reports, call-admins, and claim-logs discord channels.
2. Do discord bot commands: 
- /configure -> report -> #reports
- /configure -> calladmin -> #call-admins
- /configure -> reports -> #claim-logs
3. Test them by doing `/calladmin test` in-game.
4. Check call-admins channel to see if it posted.
5. It doesn't post.

**Expected behavior**
It is supposed to log those options in those channels.

**Screenshots/Logs**
https://youtu.be/nkfO_xgW0n0

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version: 5652
 - EasyAdmin Version: 6.7

**Additional context**
- I haven't changed any source code relating to webhook logging for the bot nor the bot itself. I installed this latest version about a week ago.
- I have checked and made sure that the bot is able to post in the discord channels. I have also given bot full administrator permissions to maybe see if it would've fixed the bug. Spoiler alert, it did not.
- If there were a problem on my own part, what did I do wrong (in the video) that caused only these log forwards to bug out compared to others that I've shown (claim logs in the video)?

**Comment by tristencommunity** [comment] 2022-06-26 08:03
It is 3AM and I have shut down my 2nd client and server for the night as I am writing this, but I'm pretty sure that the option: ``ban`` does not log forward either if I remember when I first testing it.

If you want a copy of my EasyAdmin configuration (i have it under its own .cfg file), let me know and I'll happily send it over on here.

**Comment by Blumlaut** [comment] 2022-06-26 09:22
Thanks for the detailed bug report! I'll try reproducing this.

**Comment by Blumlaut** [comment] 2022-06-26 09:40
Okay, as far as reports and calladmin forwarding go, it seems i actually forgot implementing the forwarding logic there, added in https://github.com/Blumlaut/EasyAdmin/commit/dd963718f09b557898e367c6f01d33daa2f9e986

However, i could not reproduce `ban` failing to forward, seems to work fine on my end.

**Comment by Blumlaut** [comment] 2022-06-28 15:58
i'll close this issue as the actual calladmin/report issue has been fixed, reopen if i missed anything.

**Closed by Blumlaut** 2022-06-28 15:58 UTC
Labels: bug
