### ISSUE TITLE
menu takes long time to open (6.202+)

### ISSUE THREAD

**Issue by maxcamorra** [Blumlaut/EasyAdmin#269] opened 2021-10-19 12:48 UTC
the latest update is lagging so heavy, it needs 5 secs or more to open easyadmin and to change something, if there are more than 10 players. if there are only 2 or so it works perfectly fine.

**Comment by maxcamorra** [comment] 2021-10-19 23:33
its not fixed i added it on 4 pm and then restarted the server and it still needs 5 sec to open

**Comment by Blumlaut** [comment] 2021-10-20 03:19
which ref are you on, are you actually on master? this must be an entirely different issue as someone else reported their issue at 80+ players was fixed otherwise

**Comment by maxcamorra** [comment] 2021-10-20 12:02
yes im on master and it also show me this inside the console although I installed the latest release :D
![image](https://user-images.githubusercontent.com/78707245/138088872-bcdb4457-2f9c-4dc4-a40b-46e97b25f748.png)

**Comment by Blumlaut** [comment] 2021-10-20 13:26
Can you try using this:
https://github.com/Blumlaut/EasyAdmin/archive/d0c9627a93bc45d72cf8e523bb1ea60ccbea913e.zip

Does it occur then too?

**Comment by maxcamorra** [comment] 2021-10-20 15:16
still the same problem

**Comment by maxcamorra** [comment] 2021-10-20 15:26
i have tried but where do i find the file now? i use linux :D

**Comment by Blumlaut** [comment] 2021-10-20 15:47
alternatively i need some infos to be able to fully reproduce this, as myself i cant seem to repro it even with 150 players..

**Comment by Blumlaut** [comment] 2021-10-20 15:51
Well something in your setup must be causing this delay, are you using a local server or remote? any plugins? what other resources have you running? server specs? etc etc etc etc

**Comment by Blumlaut** [comment] 2021-10-20 15:54
> til i updated on 6.202

which version did you run before then? 6.202? You said you ran on master branch earlier, did you also try the [actual release?](https://github.com/Blumlaut/EasyAdmin/releases/tag/6.202).

6.202 did not use latent events yet so something else on your server must be causing it, can you run the same profiler reading on the **Server** once and open the link it gives you in the console in chrome? i suspect your server is hitching..
`profiler record 25` should do for server-side recordings as its just a tiny overview of tick length, nothing precise.

**Comment by Blumlaut** [comment] 2021-10-20 16:26
right off the bat your server is chugging extremely hard, it seems your "saltyradio" resource is running _extremely_ slow, same with esx_status and a few others:
![image](https://user-images.githubusercontent.com/13604413/138132396-cb213db3-c4cd-440f-af97-f51a895e3b0b.png)
![image](https://user-images.githubusercontent.com/13604413/138132450-e968025f-57a6-4929-8160-a0ecb3c6bc2d.png)
![image](https://user-images.githubusercontent.com/13604413/138132505-f43157db-04dc-4a61-9a9c-233d9443b99b.png)
![image](https://user-images.githubusercontent.com/13604413/138132540-0c2fc025-67c4-49c4-a6c7-105ca3baeda9.png)

This could already be the reason why the easyadmin event is seemingly stalling for too long.
try running `netEventLog 1` in the ingame console and see whats going on there in terms of event sizes, also would be interesting to see how big the "EasyAdmin:GetInfinityPlayerList" is.

**Comment by maxcamorra** [comment] 2021-10-20 16:39
![image](https://user-images.githubusercontent.com/78707245/138134967-faec6d1e-111d-46e6-a6fa-76bc56e94ff4.png)

**Comment by Blumlaut** [comment] 2021-10-20 17:48
20kb.. thats nothing.

Yeah im almost certain this is caused by your server lagging somehow, i dont know your individual resources but i reckon if you look at the resources in the screenshots i sent above that might get you somewhere. since it happens both pre- and post the LatentEvent commit i highly doubt its actually caused by an EasyAdmin Update as nothing was changed between 6.2 and 6.202 that would explain anything like this.

**Comment by Blumlaut** [comment] 2021-10-20 19:51
well you can gladly go hop versions and see which exact update caused it, i just compared 6.0 to 6.202 and absolutely nothing was changed, and i cant reproduce it, nor can the guy that reported another issue which is fixed in master now, so until you can somehow provide a repro which i dont need to artifically lag my server with bad resources with, nothing i can fix.

**Closed as completed** 2021-10-24 23:37 UTC
Labels: bug, repro-needed, master-branch
