### ISSUE TITLE
[BUG] EasyAdmin menu doesn't work while spectating

### ISSUE THREAD

**Issue by LxrsV1-YT** [Blumlaut/EasyAdmin#495] opened 2022-09-19 17:54 UTC
Hello,

If I spectate someone using EasyAdmin, my menu closes and I can't open it again for a few minutes (or I have to restart the EasyAdmin Script). Does anyone know a solution? Thanks!

Kind regards

**Comment by Blumlaut** [comment] 2022-09-24 04:13
getting any errors? is this a duplicate of #448?

**Closed** 2022-09-24 04:14 UTC
Labels: bug, repro-needed
