### ISSUE TITLE
Spectate dont work correctly

### ISSUE THREAD

**Issue by johnsoul777** [Blumlaut/EasyAdmin#175] opened 2020-12-05 23:35 UTC
I am using the latest version and now if I can see everyone, the problem is that when I press E I appear in the position of the person I was seeing, I am using OneSync Infinity

**Comment by Blumlaut** [comment] 2020-12-05 23:45
I could not reproduce this on my side i'm afraid, could you record a video of the issue, also make sure to attach screenshots (or show in the video) of the ingame and server console

**Comment by johnsoul777** [comment] 2020-12-05 23:55
look bro! https://streamable.com/w9hnat

**Comment by Jaccosf** [comment] 2020-12-06 00:14
Same issue here: You can spectate anyone, but you will be teleported to their location when you stop spectating.

**Comment by Blumlaut** [comment] 2020-12-06 00:24
@johnsoul777, sadly the video you provided doesn't show either of the Console's output, please send screenshots of both either in this issue or in the support-ea channel on discord!
this same goes for @Jaccosf, please provide these infos so i can take a closer look!

**Comment by johnsoul777** [comment] 2020-12-06 00:30
@Blumlaut The question is, no error is shown either in RCON or in the server console, I don't know what can happen ...

**Comment by Blumlaut** [comment] 2020-12-06 00:31
Make sure to check the *ingame* console (F8)

**Comment by johnsoul777** [comment] 2020-12-06 00:42
@Blumlaut Here's another test, I don't understand what happens... https://streamable.com/a45mws

**Comment by Jaccosf** [comment] 2020-12-06 13:05
@Blumlaut https://streamable.com/r3f35h In this video, I will spectate someone, but when I will stop, I will be at the same location as they are.

**Comment by Blumlaut** [comment] 2020-12-06 13:27
please try and see if commit https://github.com/Blumlaut/EasyAdmin/commit/360ad8de880eb4e7188281ad4d117f2aa53c4907 fixes this issue @johnsoul777 @Jaccosf

**Comment by johnsoul777** [comment] 2020-12-06 19:33
@Blumlaut you are the best bro, now works correctly, thanks!!!

**Comment by johnsoul777** [comment] 2020-12-06 19:35
only not work the bring

**Comment by Blumlaut** [comment] 2020-12-06 20:13
> only not work the bring
what exactly doesnt work there?

**Comment by johnsoul777** [comment] 2020-12-06 22:01
> > sólo que no funciona el traer 
> > lo que no funciona exactamente allí?

it does not work to bring the player

**Comment by Blumlaut** [comment] 2020-12-07 00:55
I need more infos on this matter, i would recommend creating a new issue with _exact_ details, similar to what i asked above, i will close this issue here now as this issue has been fixed and will be shipped with the next hotfix

**Closed by Blumlaut** 2020-12-07 00:55 UTC
Labels: bug, needs reproducible
