### ISSUE TITLE
node_modules probleme

### ISSUE THREAD

**Issue by Ultra-Meloncrafter** [Blumlaut/EasyAdmin#494] opened 2022-09-18 17:41 UTC
I know this my third post, but there is a error spammed from easyadmin 
```
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): Error: Expected token to be set for this request, but none was present
[    script:EasyAdmin] > _RequestManager.resolveRequest (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/RequestManager.cjs:142)
[    script:EasyAdmin] > _RequestManager.queueRequest (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/RequestManager.cjs:115)
[    script:EasyAdmin] > REST.raw (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:56)
[    script:EasyAdmin] > REST.request (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:52)
[    script:EasyAdmin] > REST.get (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:37)
[    script:EasyAdmin] > ChannelManager.fetch (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/discord.js/src/managers/ChannelManager.js:123)
[    script:EasyAdmin] > updateServerStatus (@EasyAdmin/server/bot/server_status.js:90)
```
if you now say the token is not correct set, if i restart the script it works and i configured it like the guide it says

**Comment by Blumlaut** [comment] 2022-09-18 17:56
provide a full error log or a repro.

**Comment by Ultra-Meloncrafter** [comment] 2022-09-18 18:04
```
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): Error: Expected token to be set for this request, but none was present
[    script:EasyAdmin] > _RequestManager.resolveRequest (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/RequestManager.cjs:142)
[    script:EasyAdmin] > _RequestManager.queueRequest (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/RequestManager.cjs:115)
[    script:EasyAdmin] > REST.raw (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:56)
[    script:EasyAdmin] > REST.request (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:52)
[    script:EasyAdmin] > REST.get (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/@discordjs/rest/dist/lib/REST.cjs:37)
[    script:EasyAdmin] > ChannelManager.fetch (/home/FXServer/server-data/resources/[admin]/EasyAdmin/node_modules/discord.js/src/managers/ChannelManager.js:123)
[    script:EasyAdmin] > updateServerStatus (@EasyAdmin/server/bot/server_status.js:90) 
``` this is all the console gives me and i don't know how to reproduct it, i only configured the bot like the guide says, i also reinstalled easyadmin and yarn

**Comment by Blumlaut** [comment] 2022-09-30 09:54
no valid repro, cannot reproduce this on a clean 6.9(1) install, closing.

**Closed by Blumlaut** 2022-09-30 09:54 UTC
Labels: support
